FROM docker.cnb.cool/gscore-mirror/gscore-docker:latest

USER root

RUN apt update && apt-get install -y \
    nodejs \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN uv pip install --system playwright && \
    uv run playwright install chromium && \
    playwright install-deps
